// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64
// +build 386 amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//     *bpfObjects
//     *bpfPrograms
//     *bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KprobeDevQueueXmit         *ebpf.ProgramSpec `ebpf:"kprobe_dev_queue_xmit"`
	KprobeEthTypeTrans         *ebpf.ProgramSpec `ebpf:"kprobe_eth_type_trans"`
	KprobeIpLocalDeliverFinish *ebpf.ProgramSpec `ebpf:"kprobe_ip_local_deliver_finish"`
	KprobeIpLocalOut           *ebpf.ProgramSpec `ebpf:"kprobe_ip_local_out"`
	KprobeIpProtocolDeliverRcu *ebpf.ProgramSpec `ebpf:"kprobe_ip_protocol_deliver_rcu"`
	KprobeIpQueueXmit          *ebpf.ProgramSpec `ebpf:"kprobe_ip_queue_xmit"`
	KprobeIpRcv                *ebpf.ProgramSpec `ebpf:"kprobe_ip_rcv"`
	KprobeTcpDataQueue         *ebpf.ProgramSpec `ebpf:"kprobe_tcp_data_queue"`
	KprobeTcpRcvEstablished    *ebpf.ProgramSpec `ebpf:"kprobe_tcp_rcv_established"`
	KprobeTcpTransmitSkb       *ebpf.ProgramSpec `ebpf:"kprobe_tcp_transmit_skb"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	CurrentTime *ebpf.MapSpec `ebpf:"current_time"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	PidforUser  *ebpf.MapSpec `ebpf:"pidfor_user"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	CurrentTime *ebpf.Map `ebpf:"current_time"`
	Events      *ebpf.Map `ebpf:"events"`
	PidforUser  *ebpf.Map `ebpf:"pidfor_user"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.CurrentTime,
		m.Events,
		m.PidforUser,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KprobeDevQueueXmit         *ebpf.Program `ebpf:"kprobe_dev_queue_xmit"`
	KprobeEthTypeTrans         *ebpf.Program `ebpf:"kprobe_eth_type_trans"`
	KprobeIpLocalDeliverFinish *ebpf.Program `ebpf:"kprobe_ip_local_deliver_finish"`
	KprobeIpLocalOut           *ebpf.Program `ebpf:"kprobe_ip_local_out"`
	KprobeIpProtocolDeliverRcu *ebpf.Program `ebpf:"kprobe_ip_protocol_deliver_rcu"`
	KprobeIpQueueXmit          *ebpf.Program `ebpf:"kprobe_ip_queue_xmit"`
	KprobeIpRcv                *ebpf.Program `ebpf:"kprobe_ip_rcv"`
	KprobeTcpDataQueue         *ebpf.Program `ebpf:"kprobe_tcp_data_queue"`
	KprobeTcpRcvEstablished    *ebpf.Program `ebpf:"kprobe_tcp_rcv_established"`
	KprobeTcpTransmitSkb       *ebpf.Program `ebpf:"kprobe_tcp_transmit_skb"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeDevQueueXmit,
		p.KprobeEthTypeTrans,
		p.KprobeIpLocalDeliverFinish,
		p.KprobeIpLocalOut,
		p.KprobeIpProtocolDeliverRcu,
		p.KprobeIpQueueXmit,
		p.KprobeIpRcv,
		p.KprobeTcpDataQueue,
		p.KprobeTcpRcvEstablished,
		p.KprobeTcpTransmitSkb,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
